import { EventEmitter } from 'node:events'
import { afterEach, expect, it, vi } from 'vitest'
import { AppUpdater, UPDATE_INTERVAL_MS, UPDATE_START_DELAY_MS, updateFeedURL } from '../src/main/app-updater'

const controllers: AppUpdater[] = []
afterEach(() => { controllers.splice(0).forEach((item) => item.dispose()); vi.useRealTimers() })
function fixture(supported = true) {
  const updater = Object.assign(new EventEmitter(), { setFeedURL: vi.fn(), checkForUpdates: vi.fn(), getFeedURL: vi.fn(), quitAndInstall: vi.fn() })
  const showMessage = vi.fn().mockResolvedValue({ response: 1 })
  const publish = vi.fn()
  const notifyReady = vi.fn()
  const install = vi.fn().mockResolvedValue(undefined)
  const controller = new AppUpdater({ updater, supported, arch: 'arm64', version: '0.0.22', showMessage, publish, notifyReady, install })
  controllers.push(controller)
  controller.start()
  return { controller, updater, showMessage, notifyReady, install, publish }
}

it('selects the native architecture feed and rejects unsupported architectures', () => {
  expect(updateFeedURL('arm64')).toContain('/arm64/latest.json')
  expect(updateFeedURL('x64')).toContain('/x64/latest.json')
  expect(() => updateFeedURL('ia32')).toThrow('Unsupported')
})
it('checks after startup and every six hours, without overlapping downloads', async () => {
  vi.useFakeTimers()
  const { updater, controller } = fixture()
  await vi.advanceTimersByTimeAsync(UPDATE_START_DELAY_MS - 1)
  expect(updater.checkForUpdates).not.toHaveBeenCalled()
  await vi.advanceTimersByTimeAsync(1)
  expect(updater.setFeedURL).toHaveBeenCalledWith({ url: updateFeedURL('arm64'), serverType: 'json' })
  expect(controller.menuState).toEqual({ label: 'Checking for Updates…', enabled: false })
  updater.emit('update-available')
  await controller.check()
  await vi.advanceTimersByTimeAsync(UPDATE_INTERVAL_MS)
  expect(updater.checkForUpdates).toHaveBeenCalledTimes(1)
  expect(controller.menuState.label).toBe('Downloading Update…')
  updater.emit('update-not-available')
  await vi.advanceTimersByTimeAsync(UPDATE_INTERVAL_MS)
  expect(updater.checkForUpdates).toHaveBeenCalledTimes(2)
})
it('keeps background checks quiet and reports manual results', async () => {
  const { controller, updater, showMessage } = fixture()
  await controller.check(false)
  updater.emit('update-not-available')
  expect(showMessage).not.toHaveBeenCalled()
  await controller.check()
  updater.emit('update-not-available')
  expect(showMessage).toHaveBeenCalledWith(expect.objectContaining({ detail: 'You are running version 0.0.22.' }))
})
it('recovers from feed initialization and network errors for a later retry', async () => {
  const { controller, updater, showMessage } = fixture()
  updater.setFeedURL.mockImplementationOnce(() => { throw new Error('unsigned') })
  await controller.check()
  expect(controller.menuState.enabled).toBe(true)
  expect(showMessage).toHaveBeenCalledWith(expect.objectContaining({ type: 'error' }))
  await controller.check(false)
  expect(updater.setFeedURL).toHaveBeenCalledTimes(2)
  showMessage.mockClear()
  updater.emit('error', new Error('offline'))
  expect(showMessage).not.toHaveBeenCalled()
  expect(controller.menuState.enabled).toBe(true)
  await controller.check()
  expect(updater.checkForUpdates).toHaveBeenCalledTimes(2)
})
it('notifies on background download, keeps Later pending, and installs only after restart confirmation', async () => {
  const { controller, updater, notifyReady, showMessage, install } = fixture()
  await controller.check(false)
  updater.emit('update-downloaded')
  expect(notifyReady).toHaveBeenCalledTimes(1)
  expect(showMessage).not.toHaveBeenCalled()
  expect(controller.menuState).toEqual({ label: 'Restart to Update…', enabled: true })
  await controller.check()
  expect(install).not.toHaveBeenCalled()
  showMessage.mockResolvedValueOnce({ response: 0 })
  await controller.check()
  expect(install).toHaveBeenCalledTimes(1)
  expect(controller.menuState.enabled).toBe(false)
})
it('does not stack restart prompts or install twice on repeated menu clicks', async () => {
  const { controller, updater, showMessage, install } = fixture()
  let answer!: (value: { response: number }) => void
  showMessage.mockReturnValueOnce(new Promise((resolve) => { answer = resolve }))
  await controller.check()
  updater.emit('update-downloaded')
  await controller.check()
  await controller.check()
  expect(showMessage).toHaveBeenCalledTimes(1)
  answer({ response: 0 })
  await Promise.resolve()
  await Promise.resolve()
  expect(install).toHaveBeenCalledTimes(1)
})
it('never contacts the feed in development and stops scheduled checks on disposal', async () => {
  vi.useFakeTimers()
  const dev = fixture(false)
  await vi.advanceTimersByTimeAsync(UPDATE_INTERVAL_MS)
  await dev.controller.check()
  expect(dev.updater.setFeedURL).not.toHaveBeenCalled()
  expect(dev.updater.checkForUpdates).not.toHaveBeenCalled()
  const prod = fixture()
  prod.controller.dispose()
  await vi.advanceTimersByTimeAsync(UPDATE_INTERVAL_MS)
  await prod.controller.check()
  expect(prod.updater.checkForUpdates).not.toHaveBeenCalled()
})

it('absorbs late native updater errors while the helper is shutting down', () => {
  const { controller, updater } = fixture()
  controller.dispose()
  expect(() => updater.emit('error', new Error('late network error'))).not.toThrow()
})

it('retries when native initialization emits an error without throwing', async () => {
  const { controller, updater } = fixture()
  updater.setFeedURL.mockImplementationOnce(() => updater.emit('error', new Error('native init failed')))
  await controller.check(false)
  expect(updater.checkForUpdates).not.toHaveBeenCalled()
  expect(controller.menuState.enabled).toBe(true)
  await controller.check(false)
  expect(updater.setFeedURL).toHaveBeenCalledTimes(2)
  expect(updater.checkForUpdates).toHaveBeenCalledTimes(1)
})
