import { afterEach, expect, it } from 'vitest'
import { mkdtemp, writeFile, readFile, rm, rename } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { gitCommand, gitSnapshot, stageFiles, unstageFiles, commitStaged, commitFiles, commitDiff, fileDiff } from '../src/main/git'
const roots: string[] = []
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))) })
async function repo() {
  const root = await mkdtemp(path.join(tmpdir(), 'buddy-git-review-')); roots.push(root)
  await gitCommand(root, ['init', '-b', 'main'])
  await gitCommand(root, ['config', 'user.name', 'Buddy Test'])
  await gitCommand(root, ['config', 'user.email', 'buddy@example.invalid'])
  await gitCommand(root, ['config', 'commit.gpgsign', 'false'])
  return root
}
it('stages exact literal files, handles unborn unstage and commits only existing index', async () => {
  const root = await repo()
  await writeFile(path.join(root, ':(glob)*'), 'literal\n')
  await writeFile(path.join(root, 'unrelated'), 'preserve\n')
  expect((await gitSnapshot(root)).files).toHaveLength(2)
  await stageFiles(root, [':(glob)*'])
  expect(await gitCommand(root, ['diff', '--cached', '--name-only'])).toBe(':(glob)*\n')
  await unstageFiles(root, [':(glob)*'])
  expect(await gitCommand(root, ['ls-files'])).toBe('')
  expect(await readFile(path.join(root, ':(glob)*'), 'utf8')).toBe('literal\n')
  await stageFiles(root, [':(glob)*'])
  const hash = await commitStaged(root, 'Initial selected file')
  expect(await commitFiles(root, hash)).toEqual([{ path: ':(glob)*', status: 'A' }])
  expect(await commitDiff(root, hash, ':(glob)*')).toContain('+literal')
  expect((await gitSnapshot(root)).files).toEqual([{ path: 'unrelated', status: '??', lineStats: { added: 1, removed: 0 } }])
  await expect(stageFiles(root, ['.'])).rejects.toThrow()
  await expect(stageFiles(root, ['../escape'])).rejects.toThrow()
  await expect(commitStaged(root, '')).rejects.toThrow()
  await expect(commitStaged(root, 'No staged files')).rejects.toThrow('No staged')
})
it('preserves partial staging and supports deleted files and rename history', async () => {
  const root = await repo()
  await writeFile(path.join(root, 'old.txt'), 'one\ntwo\nthree\n')
  await writeFile(path.join(root, 'delete.txt'), 'delete me\n')
  await stageFiles(root, ['old.txt', 'delete.txt'])
  await commitStaged(root, 'Base files')
  await rename(path.join(root, 'old.txt'), path.join(root, 'new.txt'))
  await stageFiles(root, ['old.txt', 'new.txt'])
  const renamed = (await gitSnapshot(root)).files.find((file) => file.path === 'new.txt')
  expect(renamed).toMatchObject({ status: 'R ', originalPath: 'old.txt' })
  await unstageFiles(root, ['new.txt'])
  expect(await gitCommand(root, ['diff', '--cached', '--name-only'])).toBe('')
  await stageFiles(root, ['old.txt', 'new.txt'])
  const hash = await commitStaged(root, 'Rename selected file')
  expect(await commitFiles(root, hash)).toEqual([{ path: 'new.txt', originalPath: 'old.txt', status: 'R100' }])
  expect(await commitDiff(root, hash, 'new.txt')).toContain('rename from old.txt')
  await writeFile(path.join(root, 'new.txt'), 'staged\n')
  await stageFiles(root, ['new.txt'])
  await writeFile(path.join(root, 'new.txt'), 'unstaged\n')
  await commitStaged(root, 'Index version only')
  expect(await gitCommand(root, ['show', 'HEAD:new.txt'])).toBe('staged\n')
  expect(await readFile(path.join(root, 'new.txt'), 'utf8')).toBe('unstaged\n')
  await rm(path.join(root, 'delete.txt'))
  await stageFiles(root, ['delete.txt'])
  expect(await fileDiff(root, 'delete.txt')).toContain('-delete me')
  await unstageFiles(root, ['delete.txt'])
  expect((await gitSnapshot(root)).files.find((file) => file.path === 'delete.txt')?.status).toBe(' D')
  await expect(commitDiff(root, '--all', 'new.txt')).rejects.toThrow('full commit hash')
  await expect(commitDiff(root, hash, 'delete.txt')).rejects.toThrow('not part')
})
