// Code generated by scripts/skills/gen_catalog.py — DO NOT EDIT.
// Source of truth: the skills/ tree (one folder per skill, capabilities
// declared in skills/<name>/skill.json). Regenerate: make skills-catalog

package skills

import "go.autonomous.ai/os/system/device"

// Catalog is every skill folder in skills/, in folder order.
var Catalog = []string{
	"audio",
	"camera",
	"claude-buddy",
	"computer-use",
	"connectors",
	"display",
	"emotion",
	"face-enroll",
	"guard",
	"habit",
	"input-branching",
	"led-control",
	"mood",
	"music",
	"music-suggestion",
	"scene",
	"sensing",
	"sensing-track",
	"servo-control",
	"servo-tracking",
	"skill-creator",
	"speaker-recognizer",
	"user-emotion-detection",
	"voice",
	"wellbeing",
}

// Capability maps a skill to the ROBOT.md capabilities it requires,
// ANY-OF: the skill is kept when the device declares at least one. A skill
// absent from this map has no hardware dependency and installs everywhere.
var Capability = map[string][]string{
	"audio":  {device.CapAudio},
	"camera": {device.CapVision},
	// Needs a mic and speaker to ask out loud; harmless on audio devices with no
	// companion daemon.
	"claude-buddy": {device.CapAudio},
	"computer-use": {device.CapCompanion},
	"display":      {device.CapDisplay},
	"emotion":      {device.CapExpression},
	// Camera people-perception: the ML people-layer over the camera, not the raw
	// vision sensor — a camera that only streams must not load it.
	"face-enroll": {device.CapPresence},
	// Camera people-perception: the ML people-layer over the camera, not the raw
	// vision sensor.
	"guard":          {device.CapPresence},
	"led-control":    {device.CapLight},
	"music":          {device.CapMedia},
	"scene":          {device.CapLight},
	"sensing":        {device.CapSensing},
	"sensing-track":  {device.CapSensing},
	"servo-control":  {device.CapMotion},
	"servo-tracking": {device.CapMotion},
	// Voice people-perception: a mic is all speaker-ID needs — no camera, no
	// presence layer.
	"speaker-recognizer": {device.CapAudio},
	// One skill, two triggers: facial emotion (camera, gated on presence) and
	// speech emotion (mic, gated on audio). Loads when the device has either.
	"user-emotion-detection": {device.CapAudio, device.CapPresence},
	"voice":                  {device.CapAudio},
}
