// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"go.autonomous.ai/os/internal/agent"
	"go.autonomous.ai/os/internal/ambient"
	"go.autonomous.ai/os/internal/beclient"
	"go.autonomous.ai/os/internal/buddy"
	"go.autonomous.ai/os/internal/device"
	"go.autonomous.ai/os/internal/healthwatch"
	"go.autonomous.ai/os/internal/monitor"
	"go.autonomous.ai/os/internal/network"
	"go.autonomous.ai/os/internal/statusled"
	"go.autonomous.ai/os/lib/mqtt"
	http6 "go.autonomous.ai/os/server/agent/delivery/http"
	http7 "go.autonomous.ai/os/server/buddy/delivery/http"
	"go.autonomous.ai/os/server/config"
	http3 "go.autonomous.ai/os/server/device/delivery/http"
	mqtthandler "go.autonomous.ai/os/server/device/delivery/mqtt"
	"go.autonomous.ai/os/server/health/delivery/http"
	http2 "go.autonomous.ai/os/server/network/delivery/http"
	http5 "go.autonomous.ai/os/server/sensing/delivery/http"
)

// Injectors from wire.go:

func InitializeServer() (*Server, error) {
	configConfig := config.ProvideConfig()
	service := network.ProvideService(configConfig)
	bus := monitor.ProvideBus()
	statusledService := statusled.ProvideService(configConfig)
	agentGateway := agent.ProvideGateway(configConfig, bus, statusledService)
	personaMigration := agent.ProvidePersonaMigration(configConfig)
	channelReconcile := agent.ProvideChannelReconcile(configConfig, agentGateway)
	healthHandler := http.ProvideHealthHandler(configConfig, service, agentGateway)
	client := beclient.ProvideClient(configConfig)
	deviceService := device.ProvideService(configConfig, service, agentGateway, client)
	networkHandler := http2.ProvideNetworkHandler(configConfig, service, deviceService)
	deviceHandler := http3.ProvideDeviceHandler(deviceService, service, configConfig)
	mqttConfig := config.ProvideMQTTConfig(configConfig)
	factory, err := mqtt.ProvideFactory(mqttConfig)
	if err != nil {
		return nil, err
	}
	deviceMQTTHandler := mqtthandler.ProvideDeviceMQTTHandler(configConfig, factory, deviceService, service, agentGateway)
	agentHandler := http6.ProvideAgentHandler(agentGateway, bus, statusledService, configConfig)
	sensingHandler := http5.ProvideSensingHandler(agentGateway, bus, configConfig, statusledService, agentHandler.IsSleeping)
	ambientService := ambient.ProvideService(bus, configConfig)
	healthwatchService := healthwatch.ProvideService(bus, configConfig, statusledService)
	buddyService, err := buddy.ProvideService()
	if err != nil {
		return nil, err
	}
	buddyHandler := http7.ProvideBuddyHandler(configConfig, buddyService)
	server := ProvideServer(configConfig, healthHandler, networkHandler, deviceHandler, deviceMQTTHandler, agentHandler, sensingHandler, buddyHandler, deviceService, agentGateway, personaMigration, channelReconcile, service, factory, ambientService, healthwatchService, statusledService)
	return server, nil
}
