// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"go.autonomous.ai/os/system/agent"
	"go.autonomous.ai/os/system/ambient"
	"go.autonomous.ai/os/system/beclient"
	"go.autonomous.ai/os/system/buddy"
	"go.autonomous.ai/os/system/device"
	"go.autonomous.ai/os/system/healthwatch"
	"go.autonomous.ai/os/system/lib/mqtt"
	"go.autonomous.ai/os/system/monitor"
	"go.autonomous.ai/os/system/network"
	"go.autonomous.ai/os/system/plugin"
	http4 "go.autonomous.ai/os/system/server/agent/delivery/http"
	http6 "go.autonomous.ai/os/system/server/buddy/delivery/http"
	"go.autonomous.ai/os/system/server/config"
	http3 "go.autonomous.ai/os/system/server/device/delivery/http"
	"go.autonomous.ai/os/system/server/device/delivery/mqtt"
	"go.autonomous.ai/os/system/server/health/delivery/http"
	http2 "go.autonomous.ai/os/system/server/network/delivery/http"
	http7 "go.autonomous.ai/os/system/server/plugin/delivery/http"
	http5 "go.autonomous.ai/os/system/server/sensing/delivery/http"
	"go.autonomous.ai/os/system/statusled"
)

// Injectors from wire.go:

func InitializeServer() (*Server, error) {
	configConfig := config.ProvideConfig()
	service := network.ProvideService(configConfig)
	bus := monitor.ProvideBus()
	bool2 := provideStatusLEDHasLight(configConfig)
	statusledService := statusled.ProvideService(bool2)
	agentGateway := agent.ProvideGateway(configConfig, bus, statusledService)
	healthHandler := http.ProvideHealthHandler(configConfig, service, agentGateway)
	client := beclient.ProvideClient(configConfig)
	deviceService := device.ProvideService(configConfig, service, agentGateway, client, statusledService)
	networkHandler := http2.ProvideNetworkHandler(configConfig, service, deviceService)
	deviceHandler := http3.ProvideDeviceHandler(deviceService, service, configConfig)
	mqttConfig := config.ProvideMQTTConfig(configConfig)
	factory, err := mqtt.ProvideFactory(mqttConfig)
	if err != nil {
		return nil, err
	}
	chatStream := mqtthandler.ProvideChatStream(configConfig, factory, bus)
	deviceMQTTHandler := mqtthandler.ProvideDeviceMQTTHandler(configConfig, factory, deviceService, service, agentGateway, chatStream)
	agentHandler := http4.ProvideAgentHandler(agentGateway, bus, statusledService, configConfig)
	v := provideAgentIsSleeping(agentHandler)
	sensingHandler := http5.ProvideSensingHandler(agentGateway, bus, configConfig, statusledService, v)
	buddyService, err := buddy.ProvideService()
	if err != nil {
		return nil, err
	}
	buddyHandler := http6.ProvideBuddyHandler(configConfig, buddyService)
	pluginService := plugin.ProvideService()
	pluginHandler := http7.ProvidePluginHandler(pluginService)
	personaMigration := agent.ProvidePersonaMigration(configConfig)
	configMigration := agent.ProvideConfigMigration(configConfig, agentGateway)
	channelReconcile := agent.ProvideChannelReconcile(configConfig, agentGateway)
	mcpReconcile := agent.ProvideMCPReconcile(configConfig, agentGateway)
	ambientService := ambient.ProvideService(bus, configConfig)
	healthwatchService := healthwatch.ProvideService(bus, configConfig, statusledService)
	server := ProvideServer(configConfig, healthHandler, networkHandler, deviceHandler, deviceMQTTHandler, agentHandler, sensingHandler, buddyHandler, pluginHandler, deviceService, agentGateway, personaMigration, configMigration, channelReconcile, mcpReconcile, service, factory, ambientService, healthwatchService, statusledService, chatStream)
	return server, nil
}
