#!/usr/bin/env python3
"""Generate the skill catalog from the `skills/` tree.

The tree is the source of truth. Each `skills/<name>/` folder is a skill; the
optional `skills/<name>/skill.json` sidecar declares which DEVICE.md
capabilities it needs (ANY-OF — the skill installs when the device declares at
least one). No sidecar, or no `capabilities` key, means a platform skill with
no hardware dependency: it installs everywhere.

This writes two generated artifacts, so nobody edits a list by hand:

  system/skills/catalog_gen.go   Catalog + Capability for os-server
  scripts/provision/setup.sh     the SKILLS_CATALOG line and skill_caps()
                                 body, between GENERATED markers

Run it with `make skills-catalog`. `go test ./system/skills/` fails if the
generated Go file no longer matches the tree, so a new skill folder cannot ship
without its catalog entry.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SKILLS = ROOT / "skills"
GO_OUT = ROOT / "system" / "skills" / "catalog_gen.go"
SETUP = ROOT / "scripts" / "provision" / "setup.sh"

BEGIN = "  # ---8<--- GENERATED by scripts/skills/gen_catalog.py — edit skills/<name>/skill.json"
END = "  # ---8<--- END GENERATED"

# capability name -> the device.Cap* constant os-server uses
CAP_CONST = {
    "audio": "CapAudio",
    "vision": "CapVision",
    "sensing": "CapSensing",
    "presence": "CapPresence",
    "motion": "CapMotion",
    "light": "CapLight",
    "display": "CapDisplay",
    "expression": "CapExpression",
    "lifelike": "CapLifelike",
    "media": "CapMedia",
    "connectivity": "CapConnectivity",
    "companion": "CapCompanion",
    "system": "CapSystem",
}


def read_tree():
    """[(name, [capabilities], note)] in folder order."""
    out = []
    for d in sorted(p for p in SKILLS.iterdir() if p.is_dir()):
        sidecar = d / "skill.json"
        caps, note = [], ""
        if sidecar.is_file():
            data = json.loads(sidecar.read_text())
            caps = list(data.get("capabilities", []))
            note = data.get("note", "")
            for c in caps:
                if c not in CAP_CONST:
                    raise SystemExit(
                        f"{sidecar}: unknown capability {c!r} — "
                        f"the 13 names live in devices/contract/capabilities.md"
                    )
        elif not (d / "SKILL.md").is_file():
            continue  # not a skill folder
        out.append((d.name, caps, note))
    return out


def render_go(skills):
    lines = [
        "// Code generated by scripts/skills/gen_catalog.py — DO NOT EDIT.",
        "// Source of truth: the skills/ tree (one folder per skill, capabilities",
        "// declared in skills/<name>/skill.json). Regenerate: make skills-catalog",
        "",
        "package skills",
        "",
        'import "go.autonomous.ai/os/system/device"',
        "",
        "// Catalog is every skill folder in skills/, in folder order.",
        "var Catalog = []string{",
    ]
    lines += [f'\t"{n}",' for n, _, _ in skills]
    lines += [
        "}",
        "",
        "// Capability maps a skill to the DEVICE.md capabilities it requires,",
        "// ANY-OF: the skill is kept when the device declares at least one. A skill",
        "// absent from this map has no hardware dependency and installs everywhere.",
        "var Capability = map[string][]string{",
    ]
    for name, caps, note in skills:
        if not caps:
            continue
        if note:
            for chunk in wrap(note, 74):
                lines.append(f"\t// {chunk}")
        consts = ", ".join(f"device.{CAP_CONST[c]}" for c in caps)
        lines.append(f'\t"{name}": {{{consts}}},')
    lines += ["}", ""]
    return "\n".join(lines)


def wrap(text, width):
    words, line, out = text.split(), "", []
    for w in words:
        if line and len(line) + 1 + len(w) > width:
            out.append(line)
            line = w
        else:
            line = f"{line} {w}".strip()
    if line:
        out.append(line)
    return out


def render_shell(skills):
    names = " ".join(n for n, _, _ in skills)
    lines = [
        BEGIN,
        "  SKILLS_CATALOG=\"" + names + "\"",
        "  # Echo the capabilities a skill requires (space-separated, ANY-OF: the skill",
        "  # is kept when the device declares at least one). Empty = platform skill.",
        "  skill_caps() {",
        "    case \"$1\" in",
    ]
    for name, caps, _ in skills:
        if not caps:
            continue
        value = " ".join(caps)
        quoted = f'"{value}"' if len(caps) > 1 else value
        lines.append(f"      {name}) echo {quoted} ;;")
    lines += [
        '      *) echo "" ;;',
        "    esac",
        "  }",
        END,
    ]
    return "\n".join(lines)


def splice_shell(text, block):
    if BEGIN in text and END in text:
        head = text[: text.index(BEGIN)]
        tail = text[text.index(END) + len(END):]
        return head + block + tail
    raise SystemExit(
        f"{SETUP}: generated markers not found — add the BEGIN/END pair around "
        f"SKILLS_CATALOG and skill_caps()"
    )


def gofmt_text(src: str) -> str:
    """Run the generated Go through gofmt when it is on PATH.

    Alignment is gofmt's job, not the generator's — but the check mode must
    compare against what the write path produces, so both go through here.
    """
    import shutil
    import subprocess

    exe = shutil.which("gofmt")
    if not exe:
        return src
    r = subprocess.run([exe], input=src, capture_output=True, text=True)
    return r.stdout if r.returncode == 0 else src


def gofmt(path: pathlib.Path) -> None:
    path.write_text(gofmt_text(path.read_text()))


def main():
    check = "--check" in sys.argv
    skills = read_tree()
    go_src = render_go(skills)
    setup_src = splice_shell(SETUP.read_text(), render_shell(skills))

    if check:
        stale = []
        if not GO_OUT.is_file() or GO_OUT.read_text() != gofmt_text(go_src):
            stale.append(str(GO_OUT.relative_to(ROOT)))
        if SETUP.read_text() != setup_src:
            stale.append(str(SETUP.relative_to(ROOT)))
        if stale:
            print("stale, run `make skills-catalog`: " + ", ".join(stale), file=sys.stderr)
            return 1
        print(f"catalog up to date — {len(skills)} skills")
        return 0

    GO_OUT.write_text(go_src)
    gofmt(GO_OUT)
    SETUP.write_text(setup_src)
    print(f"{len(skills)} skills → {GO_OUT.relative_to(ROOT)}, {SETUP.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
