package httpapi

import (
	"context"
	"errors"
)

// Ports — the interfaces the delivery layer depends on. Concrete
// implementations are provided by package main, so the HTTP layer never imports
// the BLE / state-machine internals (dependency inversion).

// StatusProvider exposes a read-only snapshot of buddy state.
type StatusProvider interface {
	Status() Status
}

// Status is a transport-agnostic snapshot of the device's buddy state.
type Status struct {
	State           string
	Connected       bool
	SessionsRunning int
	TokensToday     int
	HasPending      bool
	PendingID       string
	PendingTool     string
	PendingHint     string
}

// ApprovalService runs the voice-approval use case: validate the pending
// prompt, relay the decision over BLE, and update the counters.
type ApprovalService interface {
	Approve(id string) error
	Deny(id string) error
}

// Sentinel errors the approval handler maps to HTTP 409 Conflict.
var (
	ErrNoPending      = errors.New("no pending prompt")
	ErrPromptMismatch = errors.New("prompt id mismatch")
)

// CodeApprovalRequest describes a Claude Code permission prompt forwarded by the
// plugin's PreToolUse/PermissionRequest hook on the Mac.
type CodeApprovalRequest struct {
	ID    string         // correlation id, generated by the hook
	Tool  string         // e.g. "Bash", "Edit", "mcp__server__tool"
	Hint  string         // short human string for TTS/LED (derived if empty)
	Input map[string]any // raw tool_input, for richer device rendering
}

// CodeApprovalService is the Claude Code reverse-approval use case: a remote hook
// asks for a decision and BLOCKS on Request until the on-device agent resolves it
// (Approve/Deny) or the request times out. This is the HTTP mirror of the BLE
// Claude Desktop ApprovalService — the decision flows back as the hook's return
// value instead of a BLE permission message.
type CodeApprovalService interface {
	// Request registers a pending approval, triggers the device cue, and blocks
	// until resolved or timed out. Returns "allow", "deny", or "timeout".
	Request(ctx context.Context, req CodeApprovalRequest) (string, error)
	// Approve / Deny resolve a pending request by id. ErrNoPending if the id is
	// unknown or already resolved.
	Approve(id string) error
	Deny(id string) error
	// Pending lists the currently-blocked requests (for /status visibility).
	Pending() []CodeApprovalRequest
}

// ActivitySink receives Claude Code activity pushed by the plugin. The current
// implementation just logs; the device bridge (HAL: LED / display / voice) will
// implement this same interface later without touching the delivery layer.
type ActivitySink interface {
	Notify(level, title, subtitle string, sound bool)
	Usage(fiveHour, sevenDay int, reset5h, reset7d string, sound bool)
}
